# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libXfontcache
Summary:    X.Org X11 libXfontcache runtime library
Version:    1.0.5
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://www.x.org
Source0:    ftp://ftp.x.org/pub/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXfontcache.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(fontcacheproto)


%description
X-TrueType font cache extension client library


%package devel
Summary:    X.Org X11 libXfontcache development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
X-TrueType font cache extension client development library


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc COPYING ChangeLog
%{_libdir}/libXfontcache.so.1
%{_libdir}/libXfontcache.so.1.0.0
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libXfontcache.so
%dir %{_libdir}/pkgconfig
%{_libdir}/pkgconfig/xfontcache.pc
%{_mandir}/man3/*.3*
# << files devel

